POST http://localhost:8080/registerStudent
Content-Type: application/json

{
  "student": {
    "name": "山田 太郎",
    "kanaName": "やまだ たろう",
    "nickname": "たっちゃん",
    "email": "yamada@example.com",
    "area": "東京都",
    "age": 25,
    "sex": "男性",
    "remark": "特に問題なし"
  },
  "studentCourses": [
    {
      "courseName": "Java",
      "courseStartAt": "2025-02-01",
      "courseEndAt": "2025-06-30"
    }
  ]
}